FROM sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.10_7_1.10.0_2.13.14

WORKDIR /app

COPY src/datamart/build.sbt ./build.sbt
COPY src/datamart/project ./project
RUN sbt update

COPY src/datamart ./src/datamart
WORKDIR /app/src/datamart

EXPOSE 8090

CMD ["sbt", "run"]
